- name: install and run nginx
  hosts: web
  become: yes #root access
  tasks:
  - name: install nginx package
    ansible.builtin.package:
      name: nginx
      stage: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      stage: started