- name: variable from play level
  hosts: localhost
  vars_files:
    - variable.yaml
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: " hi, i am learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"