- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.state}}" # item is default keyword
    loop: 
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'present'}
    - {name: 'nginx', state: 'absent'}
  
